### ISSUE TITLE
Remove git submodules

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/embedded-bdf#7]
The `bdf-parser` crate contains two submodules for the tests. These submodules are also unnecessarily pulled if a create in this repo is added as a git dependency, which can increase build times significantly because the submodules are large (~250MB). I would really like to remove this overhead.

@jamwaffles Do you have a good idea how this could be solved? Should we only test some BDF files, which would be included in this repo?

**Comment by jamwaffles** [comment]
The simplest option would be to copy all the test files from the subdmodules into this repo. They don't really need to stay up to date with the other repos, just provide a decent test suite for the parser.

**Comment by rfuest** [comment]
But this wouldn't really help with the problem, because instead of having to check out another huge repo this repo would be huge itself.

We could split the parser test into two parts: The first part would be run by `cargo test` and it would only test a limited number of BDF files, that would be included in this repo. The other part would be run by the justfile and would checkout the other repos to a temporary directory before running the parser test on these files.

**Comment by jamwaffles** [comment]
Ah ok, I didn't realise it's the BDF files themselves which are huge.

That sounds like a much better approach. Would it run in CI or would it be run manually?

**Comment by rfuest** [comment]
It would run in CI. The CI runtime shouldn't be affected much by this change.

We could also optimize the CI runtime by running the parser tests for the external BDF files in release mode, which makes a huge difference in runtime on my system.
